name: Run tests

on:
  push:
    paths: ["**.[rR]", "**.[qrR]md"]
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Set up R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages:
          any::data.table
          any::testthat
    
    - name: Run tests
      run: Rscript -e "source(\"work/parsers.R\");
          library(testthat);
          test_dir("tests")"